name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: "CI"
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build
        run: ./build_release.sh
      - name: Build DMG
        run: |
          npm install -g appdmg
          appdmg appdmg.json build/Release/Illusion.dmg
      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: Illusion
          path: ./build/Release
