name: "CI"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: MacOS version
        run: sw_vers
      - name: CPU information
        run: sysctl -n machdep.cpu.brand_string
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build
        run: ./build_release.sh
      - name: Build DMG
        run: |
          npm install -g appdmg
          mkdir -p ./build/dmg/Illusion
          appdmg ./appdmg.json ./build/dmg/Illusion/Illusion.dmg
      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: Illusion
          path: ./build/dmg/Illusion
